name: Acknowledging Ping from PING abd building the project 

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: Building project
        - uses: enriikke/gatsby-gh-pages-action@v2
          with:
            access-token: ${{ secrets.ACCESS_TOKEN }}
            deploy-branch: main
            gatsby-args: --prefix-paths
          
       

      - name: PONG - Build complete after receiving ping from PING sending message
        if: github.event.action == 'ping'
        run: |
          echo "Pinging back remote repo - https://github.com/ydahal1/ping"
          curl -X POST https://api.github.com/repos/ydahal1/ping/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      
    